import type { DiscoveryProvider } from '../services/discovery.service'
import type { BuilderEndpointMeta } from '../types/builder'

export const discoveryEndpointCatalog: Record<DiscoveryProvider, BuilderEndpointMeta[]> = {
  scaleaq: [
    {
      id: 'scale-meta-company',
      provider: 'scaleaq',
      label: 'Company Info',
      method: 'GET',
      path: '/meta/company?include=all',
      description: 'Ficha de compañía completa utilizada en el discovery demo.',
      category: 'Meta',
      targetBlock: 'assets',
      sampleResponseHint: 'Devuelve datos corporativos y lista de sitios.',
    },
    {
      id: 'scale-meta-site',
      provider: 'scaleaq',
      label: 'Site Info',
      method: 'GET',
      path: '/meta/sites/{siteId}?include=all',
      description: 'Información detallada del centro seleccionado.',
      category: 'Meta',
      targetBlock: 'assets',
      sampleResponseHint: 'Incluye jaulas, ubicación, biomass target.',
      params: [{ name: 'siteId', label: 'Site ID', required: true, placeholder: 'CL-REL-01' }],
    },
    {
      id: 'scale-ts-retrieve',
      provider: 'scaleaq',
      label: 'Time Series Retrieve',
      method: 'POST',
      path: '/time-series/retrieve',
      description:
        'Consulta cruda de series basadas en canales/timeRange. Útil para oxígeno, alimento y biomasa.',
      category: 'Time Series',
      targetBlock: 'timeseries',
      sampleResponseHint: 'Devuelve arrays por canal con timestamps.',
      params: [
        {
          name: 'channels',
          label: 'Channels',
          required: true,
          placeholder: 'oxygen_ppm, feeding_rate',
          helperText: 'Lista separada por coma de channels permitidos.',
        },
        {
          name: 'range',
          label: 'Rango (ej. 48h)',
          required: true,
          placeholder: '48h',
        },
      ],
    },
    {
      id: 'scale-ts-data-types',
      provider: 'scaleaq',
      label: 'Available Data Types',
      method: 'POST',
      path: '/time-series/retrieve/data-types',
      description: 'Catálogo de canales y unidades disponibles para el sitio.',
      category: 'Time Series',
      targetBlock: 'assets',
      sampleResponseHint: 'Retorna labels, units y frecuencias.',
    },
    {
      id: 'scale-units-aggregate',
      provider: 'scaleaq',
      label: 'Units Aggregate',
      method: 'POST',
      path: '/time-series/retrieve/units/aggregate',
      description: 'KPIs por unidad de cultivo (consumo, biomasa, oxígeno).',
      category: 'Aggregates',
      targetBlock: 'kpis',
      params: [
        {
          name: 'units',
          label: 'Unidades',
          placeholder: 'CL-REL-01, CL-REL-08',
          helperText: 'Opcional. Por defecto retorna todas las unidades.',
        },
      ],
    },
    {
      id: 'scale-silos-aggregate',
      provider: 'scaleaq',
      label: 'Silos Aggregate',
      method: 'POST',
      path: '/time-series/retrieve/silos/aggregate',
      description: 'Resumen de stock y consumo de silos.',
      category: 'Aggregates',
      targetBlock: 'kpis',
      params: [
        {
          name: 'silos',
          label: 'IDs de Silos',
          placeholder: 'S1,S2',
        },
      ],
    },
    {
      id: 'scale-feeding-units',
      provider: 'scaleaq',
      label: 'Feeding Units',
      method: 'GET',
      path: '/feeding-dashboard/units?siteId={siteId}',
      description: 'Resumen operacional por unidad (consumo, mortalidad, alertas).',
      category: 'Feeding',
      targetBlock: 'snapshots',
      params: [{ name: 'siteId', label: 'Site ID', required: true, placeholder: 'CL-REL-01' }],
    },
    {
      id: 'scale-feeding-timeline',
      provider: 'scaleaq',
      label: 'Feeding Timeline',
      method: 'GET',
      path: '/feeding-dashboard/timeline?siteId={siteId}',
      description: 'Serie consolidada de alimento por bloques de 10 minutos.',
      category: 'Feeding',
      targetBlock: 'timeseries',
      params: [{ name: 'siteId', label: 'Site ID', required: true, placeholder: 'CL-REL-01' }],
    },
    {
      id: 'scale-analytics-kpis',
      provider: 'scaleaq',
      label: 'Analytics KPIs',
      method: 'GET',
      path: '/analytics/kpis?siteId={siteId}',
      description: 'Indicadores operacionales diarios utilizados en el demo.',
      category: 'Analytics',
      targetBlock: 'kpis',
      params: [{ name: 'siteId', label: 'Site ID', required: true, placeholder: 'CL-REL-01' }],
    },
  ],
  innovex: [
    {
      id: 'innovex-all-monitors',
      provider: 'innovex',
      label: 'All Monitors',
      method: 'GET',
      path: '/api_dataweb/all_monitors/?active=all',
      description: 'Lista monitores asociados al cliente con coordenadas y monitor_key.',
      category: 'Catálogo',
      targetBlock: 'assets',
    },
    {
      id: 'innovex-monitor-detail',
      provider: 'innovex',
      label: 'Monitor Detail',
      method: 'GET',
      path: '/api_dataweb/monitor_detail/?monitor_id={monitor_id}',
      description: 'Detalle de sensores, jaulas y profundidad por monitor.',
      category: 'Catálogo',
      targetBlock: 'assets',
      params: [
        {
          name: 'monitor_id',
          label: 'Monitor ID',
          required: true,
          placeholder: '1234',
        },
      ],
    },
    {
      id: 'innovex-monitor-sensor-last-data',
      provider: 'innovex',
      label: 'Monitor Sensor Last Data',
      method: 'GET',
      path: '/api_dataweb/monitor_sensor_last_data/?id={monitor_id}&medition=oxygen',
      description: 'Última medición por sensor para una medition específica.',
      category: 'Lecturas',
      targetBlock: 'snapshots',
      params: [
        { name: 'monitor_id', label: 'Monitor ID', required: true, placeholder: '1234' },
        {
          name: 'medition',
          label: 'Medition',
          required: true,
          placeholder: 'oxygen',
          helperText: 'oxygen | flow | weather | temperature',
        },
      ],
    },
    {
      id: 'innovex-get-last-data',
      provider: 'innovex',
      label: 'Get Last Data (sensor)',
      method: 'GET',
      path: '/api_dataweb/get_last_data/?monitor_id={monitor_id}&sensor_id={sensor_id}',
      description: 'Dato puntual de un sensor específico, ideal para alertas.',
      category: 'Lecturas',
      targetBlock: 'snapshots',
      params: [
        { name: 'monitor_id', label: 'Monitor ID', required: true },
        { name: 'sensor_id', label: 'Sensor ID', required: true },
      ],
    },
    {
      id: 'innovex-get-data-range',
      provider: 'innovex',
      label: 'Get Data Range',
      method: 'GET',
      path: '/api_dataweb/get_data_range/?monitor_id={monitor_id}&sensor_id={sensor_id}&unixtime_since=...&unixtime_until=...',
      description: 'Devuelve serie en un rango definido (máx 30 días).',
      category: 'Históricos',
      targetBlock: 'timeseries',
      params: [
        { name: 'monitor_id', label: 'Monitor ID', required: true },
        { name: 'sensor_id', label: 'Sensor ID', required: true },
        {
          name: 'range',
          label: 'Rango (ej. 2025-01-01/2025-01-03)',
          required: true,
        },
      ],
    },
    {
      id: 'innovex-monitor-sensor-time-data',
      provider: 'innovex',
      label: 'Monitor Sensor Time Data',
      method: 'GET',
      path: '/api_dataweb/monitor_sensor_time_data/?monitor_id={monitor_id}&medition=oxygen&unixtime_since=...&unixtime_until=...',
      description: 'Series agrupadas por sensor para una medition completa.',
      category: 'Históricos',
      targetBlock: 'timeseries',
      params: [
        { name: 'monitor_id', label: 'Monitor ID', required: true },
        { name: 'medition', label: 'Medition', required: true, placeholder: 'oxygen' },
        {
          name: 'range',
          label: 'Rango Unix',
          required: true,
          placeholder: '1700700000-1700786400',
        },
      ],
    },
    {
      id: 'innovex-error-table',
      provider: 'innovex',
      label: 'Error Reference',
      method: 'DOC',
      path: 'Manual Innovex – tabla de errores',
      description: 'Lista de respuestas comunes (Access Denied, Unauthorized sensor...).',
      category: 'Alertas',
      targetBlock: 'alerts',
    },
  ],
}

export type ProviderEndpointCatalog = typeof discoveryEndpointCatalog
